### ISSUE TITLE
Demo down

### ISSUE THREAD

**Issue by me4tshield** [Morgul/ui-bootstrap4#10]
Hey there :) 
your demo is currently down. There is only a whitescreen on https://morgul.github.io/ui-bootstrap4/

/cheers and thanks for your work

**Comment by Morgul** [comment]
Seems like there was a build issue with the demo site. I'll try and look at it today.

**Comment by me4tshield** [comment]
Thanks mate :)

**Comment by Morgul** [comment]
Fixed. 🎉
