### ISSUE TITLE
Progressbar

### ISSUE THREAD

**Issue by krlos2011** [Morgul/ui-bootstrap4#12]
Hello, your branch is being of great help for my project. Thank you for your support.
There are a simple bug that we have found.

### Bug description:
The type property not works properly and is writing .progress-bar-{{type}} at .progress-bar element instead of .bg-{{type}}

### Steps to reproduce the issue:
`
<uib-progressbar value="50" type="danger" class="mb-2"><b>50%</b></uib-progressbar>
`

### A simple workaround
`
<uib-progressbar value="50" class="mb-2"><b class="bg-danger">50%</b></uib-progressbar>
`

### Version of Angular, UIBS, and Bootstrap

Angular: 1.6.7

UIBS: 3.0.2

Bootstrap: 4.0.0

**Comment by Morgul** [comment]
Thanks for catching that. If you're like to try your hand at a merge request, I'd gladly take it. Otherwise, I should get to this fix this week, along with a new version release.

**Comment by YuraDubensky** [comment]
I have fixed tests and created a pull-request https://github.com/Morgul/ui-bootstrap4/pull/18.

**Comment by YuraDubensky** [comment]
@Morgul Please verify. I am really looking forward to new release as we need fixes for dropdowns and tootip for our production.

**Comment by Morgul** [comment]
I will do my best to take a look at #18 today, if I can. One way or the other, I can promise a new release by the end of the week, how's that sound?

**Comment by YuraDubensky** [comment]
@Morgul Sounds good. Thanks

**Comment by YuraDubensky** [comment]
@Morgul Hey there, how is it going with release?

**Comment by Morgul** [comment]
@YuraDubensky released v3.0.3

**Comment by YuraDubensky** [comment]
@Morgul You rock! Thanks a lot.
