### ISSUE TITLE
Tooltip wrong position causes tootlip flickering

### ISSUE THREAD

**Issue by YuraDubensky** [Morgul/ui-bootstrap4#14]
### Bug description:
When using tooltip-placement="left", tooltip tip occasionally is placed wrongly and overlaps toggle element element. So if mouse is placed close to the left border of toggle element - it causes tip to disappear immediately after show. This produces inifinite loop of show/hide tooltip while mouse is steady.

Root cause is that class 'placementClassPrefix-' is added to tip element after position is calculated.
Boostrap defines padding on ".bs-tooltip-left"so it affects tip element's width. And since tip position is calculated taking into account tip's width it result in tip being placed to much to the right and so overlapping toggle element.

### Link to minimally-working plunker that reproduces the issue:
No need for a plunker - it is easily reproducible on demo page:
https://morgul.github.io/ui-bootstrap4/#!#tooltip

### Steps to reproduce the issue:

Select tooltip placement as 'left' and place mouse close to the left edge of tooltip button.

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.9

UIBS: 3.0.2

Bootstrap: 4.0.0

**Comment by YuraDubensky** [comment]
This is bug in action (note that right tooltip edge is overlapping with toogle element)
![image](https://user-images.githubusercontent.com/6950305/36538988-f5364028-17dd-11e8-91cc-fadf8c62d501.png)

**Comment by YuraDubensky** [comment]
@Morgul Can you please give a rough estimate on a date of next release?

**Comment by Morgul** [comment]
Fixed by #18.
