### ISSUE TITLE
Pagination styling not working

### ISSUE THREAD

**Issue by gjackson12** [Morgul/ui-bootstrap4#19]
### Bug description:
When using the Pagination directive, it appears the Bootstrap styling is not applied. Easy to reproduce, just try using the directive as outlined. 

Angular: 1.6.X

**Comment by blah238** [comment]
Should have been fixed by https://github.com/Morgul/ui-bootstrap4/pull/8

**Comment by Morgul** [comment]
If you can reproduce it in codepen, or jsfiddle, that would really help us track this down. As far as I can tell, it's working:

From http://getbootstrap.com:

![image](https://user-images.githubusercontent.com/770655/37475045-c211a382-283f-11e8-837c-180329caf5bd.png)

From https://morgul.github.io/ui-bootstrap4/#!#pagination:

![image](https://user-images.githubusercontent.com/770655/37475093-e3d0f25c-283f-11e8-909b-664d1af90891.png)

**Comment by Morgul** [comment]
@gjackson12 As far as I can tell, this has been taken care of. If you're still running into problems, feel free to reopen this issue, and we'll work through them.
