### ISSUE TITLE
Demo for dropdown with template-url doesn't work

### ISSUE THREAD

**Issue by blah238** [Morgul/ui-bootstrap4#20]
### Bug description:

The "Dropdown using template" demo doesn't show the dropdown menu when clicked. It appears that the Bootstrap `show` class is not being applied when the dropdown is toggled and the `template-url` attribute is set. Manually applying the `show` class in the browser's dev tools causes the menu to appear.

### Link to minimally-working plunker that reproduces the issue:

https://morgul.github.io/ui-bootstrap4/#!#dropdown

### Steps to reproduce the issue:

1. Click the "Dropdown using template" button -- the dropdown menu is not displayed

### Version of Angular, UIBS, and Bootstrap

Angular: 1.6.1

UIBS: 3.0.3

Bootstrap: 4.0.0

**Comment by blah238** [comment]
I also noticed that `uib-dropdown` `on-toggle` doesn't work with `uib-dropdown-menu` `template-url` either, do you want a separate issue for this? I suspect they are related if not the same issue.

**Comment by Morgul** [comment]
No, we can track both with this item. Just update the title, if you want to clarify.

**Comment by blah238** [comment]
On second thought, as I keep finding more and more issues with dropdowns, I will leave this issue as-is and open up additional issues as I can make time for, and perhaps we can have another issue (or project/milestone) for tracking them all. Thankfully I can work around most of them for now.

**Comment by Morgul** [comment]
I created a project to track the dropdown issues.

😕 Sorry dropdown has as many issues as it does; I don't know if this was just poor conversion on my part, or if these issues existed in the original project.

**Comment by blah238** [comment]
Not at all, I definitely appreciate your work on this project! And yes the original UI Bootstrap dropdowns are pretty buggy to begin with as well, e.g. https://github.com/angular-ui/bootstrap/issues/6316

**Comment by Mjinx** [comment]
I've came across the above and tracked it down to 

https://github.com/Morgul/ui-bootstrap4/blob/c6553764e7f8a9c88855332abd16e71a4264080b/src/dropdown/dropdown.js#L348

for most part the template is working and the content gets injected to dom, its just the fact the "dropdownClass" is never set on the dropdownMenu. Adding the following after compiling the template would resolve the issue.

```javascript
$compile(tplContent.trim())(templateScope, function(dropdownElement) {
            var newEl = dropdownElement;
            self.dropdownMenu.replaceWith(newEl);
            self.dropdownMenu = newEl;
            $animate.addClass(self.dropdownMenu, dropdownOpenClass); //add open class to the element to be shown
            $document.on('keydown', uibDropdownService.keybindFilter);
          });
```

while tempted to fork/pull request to add the fix I'm not too familiar with the process and would hate to break things, so i highly would appreciated if someone could address the issue and see if the above is an acceptable fix.
