### ISSUE TITLE
Datepicker Popup appears huge and out of screen

### ISSUE THREAD

**Issue by hardmaster92** [Morgul/ui-bootstrap4#23]
### Bug description:
When I open the datepicker (I use a button next to the text input) it appears but everything is really huge (icons, buttons, etc.) and I can see only small part of it and everything else is out of screen.

### Link to minimally-working plunker that reproduces the issue:
The plunker given on the very official UIBS page produces the same issue

### Steps to reproduce the issue:
Set up an text input with the basic options for a working popup datepicker. Create a button with a ng-click function to set the opened state of the datepicker to true.

### Version of Angular, UIBS, and Bootstrap
AngularJS: 1.6.9
UIBS: 3.0.3
Bootstrap: 4.0.0 (final)

**Comment by stevensobotka** [comment]
It seems like there is some css missing, I added the css below which fixed the issue for me.

.fa-svg-icon {
  display: inline-block;
  vertical-align: middle;
  min-width: 1em;
  min-height: 1em;
  height: 100%;
  position: relative;
  top: -1px;
}

.fa-svg-icon svg {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}

.fa-svg-icon svg g,
.fa-svg-icon svg path {
  fill: currentColor;
}

**Comment by Morgul** [comment]
@stevensobotka if you want to make a pull request, that'd be greatly appreciated.

Either way, I'll take a look at this in the next couple of days.

**Comment by stevensobotka** [comment]
@Morgul the css I mentioned previously was in svg-icon.css and I added that file to my project. I'm not sure if this is an actual bug or if it's simply just additional css that needs to be included into a project when using ui-bootstrap4.

**Comment by Morgul** [comment]
The bug would be that the css isn't getting included with the rest of the styling properly. All you should need to do is include the ui-bootstrap css.

**Comment by hardmaster92** [comment]
That css fragment seems to fix the issue for me. Thanks.

**Comment by shoxton** [comment]
the same bug happens with the carousel directive buttons, but nothing that adding a couple of css doesnt fix it

**Comment by phazei** [comment]
Additionally, all the buttons on the calendar are btn-secondary when they should be btn-outline-secondary to closer match the previous look.  Also text-muted has the same color as btn-outline-secondary, so the non-muted calendar items should be text-body (added in bootstrap 4.1)

**Comment by Morgul** [comment]
If anyone wants to work up a PR for this, I'll gladly review/accept it; as it is, I am not going to be able to look at much with this repo for the next 6 to 8 weeks, at a minimum. (Busy season for work, and this year's already worse than last year. 🎉)

**Comment by brazorf** [comment]
I've made a plunker before i saw this issue. Mabye it can help someone
https://plnkr.co/edit/TFwi8ZDawls368uRxxxM?p=preview

**Comment by amitasaurus** [comment]
add these classes in your scss file
`.fa-svg-icon{
				svg{
					width: 16px;
					height: 16px;
				}
			}`

**Comment by lgruelas** [comment]
To solve this problem with the arrows in a carousel, I put the lines that stevensobotka said in the css file, then in the ui-bootstrap.js file I change the class that they receive from carousel-control to carousel-control-prev and next. Now it looks and work fine.
