### ISSUE TITLE
Vertical tabs not working

### ISSUE THREAD

**Issue by brazorf** [Morgul/ui-bootstrap4#24]
### Bug description:
The following code will render tabs as horizontal:
```
<uib-tabset active="active" vertical="true">
```

### Link to minimally-working plunker that reproduces the issue:
https://morgul.github.io/ui-bootstrap4/#!#tabs
Not actually a plunker, but the sample in the demo page is enough.

### Version of Angular, UIBS, and Bootstrap

Angular: 1.6.4

UIBS: 3.0.3

Bootstrap: 4.0.0

**Comment by Morgul** [comment]
Ah, yeah, the CSS for that will need to completely change from Bootstrap v3. Damn.

**Comment by ElitenetDenmark** [comment]
We need to add **.flex-column** to the template for "uib/template/tabs/tabset.html".
The line : 
`<ul class=\"nav nav-{{tabset.type || 'tabs'}}\" ng-class=\"{'nav-stacked': vertica`
change it to:
`<ul class=\"flex-column nav nav-{{tabset.type || 'tabs'}}\" ng-class=\"{'nav-stacked': vertica`

As stated here in W3 Bootstrap 4 docs:
_Add the .flex-column class to create a vertical nav_
https://www.w3schools.com/bootstrap4/bootstrap_navs.asp

**Comment by Morgul** [comment]
@ElitenetDenmark I'd be more than happy to take a merge request for this.

**Comment by Morgul** [comment]
This should be fixed on master.
