### ISSUE TITLE
Project set up description is wrong or  1 css file is not included.

### ISSUE THREAD

**Issue by mindej** [Morgul/ui-bootstrap4#26]
When setting up project SVG icons manual include is mandatory. 

`require('../node_modules/ui-bootstrap4/src/svg-icon.css');`

Otherwise, SVG icons will be messed up a lot.

**Comment by Morgul** [comment]
@mindej You're right; that file needs to be included in the default build. It's an external css dependency that one of the forks I built this from used to handle the fact that glyphicons was no longer included in Bootstrap 4.

But, everything should work "out of the box", and that includes icons.

**Comment by Morgul** [comment]
This is a duplicate of #23.
