### ISSUE TITLE
No Accordion animation

### ISSUE THREAD

**Issue by lpsBetty** [Morgul/ui-bootstrap4#35]
### Bug description:

I am using the latest versions of Angular 1, Bootstrap CSS and ui-bootstrap4. I have no glue why, but there is no animation when opening/closing the accordion, see https://codepen.io/anon/pen/XPoqPq

I tried to find out why.. it seems like `uibCollapse` is not initialized at all.

### Version of Angular, UIBS, and Bootstrap

Angular: 1.7.4

UIBS: 3.0.4

Bootstrap: 4.1.3

**Comment by Morgul** [comment]
It looks like you didn't include `angular-animation` in your bundle. If you did, could you put together a codepen with the individual deps, and not the built bundle? It will make it easier to track down if it's a breakage in Angular 1.7.X, or something else.

**Comment by lpsBetty** [comment]
@Morgul is angular-animation really required for that? because i used the original bootstrap version before and the animation was there.. 

i will try to make individual dependencies now!

**Comment by lpsBetty** [comment]
@Morgul I updated the pen with individual dependencies: https://codepen.io/anon/pen/XPoqPq

**Comment by Morgul** [comment]
No problem. :)

`ngAnimate` is a dependency of the original angular-ui bootstrap project:

> Since version 0.13.0, UI Bootstrap depends on ngAnimate for transitions and animations, such as the accordion, carousel, etc. Include ngAnimate in the module dependencies for your app in order to enable animation.

Because I just updated templates and CSS (mostly), I inherited the same dependencies. You _can_ use ui-bootstrap4 without `ngAnimate`, but you won't get animations.
