### ISSUE TITLE
SRC file

### ISSUE THREAD

**Issue by DevChrisDev** [Morgul/ui-bootstrap4#39]
Hi. May i know what can i do if i am only interested in pagination? what files should i take and what files should i take in my project. Thanks a lot man. Im sorry this is the only way i can get to you.

**Comment by DevChrisDev** [comment]
i downloaded the custom build and chose "pagination" , i copied the "ui-bootstrap-custom-tpls-3.0.5.min.js" and put in my project ,  included <script type="text/javascript" src="../src/js/ui-bootstrap-custom-tpls-3.0.5.min.js"></script>on my project. put this dependency on my module var theApp = angular.module('theApp',['ngRoute','theApp.controller','ngStorage','ui.bootstrap']); here is my module. Am i doing it right? Please guiide me i am new into this.

**Comment by Morgul** [comment]
Closing, because this seems solved.
