### ISSUE TITLE
dist files are in the docs folder?

### ISSUE THREAD

**Issue by phazei** [Morgul/ui-bootstrap4#40]
I just installed the package from bower, and the dist files are in the docs folder, is that a bug?

**Comment by Morgul** [comment]
No, it is not. :slightly_smiling_face: The `docs` folder is where github pages serves from (it was much easier to do this than the separate branch for dist files).

The npm package ignores the `docs` folder, so it's not a size concern there. Bower doesn't know to ignore it, and while I'm pretty sure bower has some ignore mechanism, at this point I no intention of officially supporting it. (It is considered deprecated even by it's own dev team.) However, If you want to put in a PR to add an ignore for docs for bower, I'll happily merge it in.
