### ISSUE TITLE
[Question]  how do I get a compiled version in a fork?

### ISSUE THREAD

**Issue by phazei** [Morgul/ui-bootstrap4#44]
Maybe you could help me, I'm not incredibly familiar with this.  Most repos I've forked had a compiled file that I'd just use.
I use bower.
I was using:
    "ui-bootstrap4": "^3.0.5"
now I'm using:
    "ui-bootstrap4": "git://github.com/MEEEEEE/ui-bootstrap4#master"

And I just include: "bower_components/ui-bootstrap4/docs/ui-bootstrap-tpls.js"
  
Do you just manually run the grunt docs task and commit it?  Any reason not including the dist task in the repo?

**Comment by Morgul** [comment]
So, the dist task _is_ in the grunt file, but something needs to run it. (There's no CI task setup for this repo that will automatically run it on commit.)

I wouldn't be against something like that being setup, but so far, I just run it when I make a new build and commit. (Near as I can tell that's how the original project worked, though their build system is a nightmare. I've slayed a few beasts, but it's still awful.) I'm completely open to any changes you might suggest.

**Comment by phazei** [comment]
I updated the version in package.json, and ran grunt docs.  It created the 3.0.6 files, but it also updated the 3.0.5 files and didn't update the `ui-bootstrap-tpls.js` or `ui-bootstrap.js` in the docs folder.  Should it be done differently?

**Comment by Morgul** [comment]
Yes, it's documented in the readme:

https://github.com/Morgul/ui-bootstrap4#building-a-release

in short, `grunt release:3.0.6`

**Comment by Morgul** [comment]
Did you get this working?

**Comment by phazei** [comment]
Yup, got it to build, and 3.0.6 is ready.  Seems the version on the demo site is using the latest version.  But the repo only has 3.0.5 under releases.  Do you just need to add the 3.0.6 tag to get it to publish?

**Comment by Morgul** [comment]
Yup. That _should_ be all you need to do.

**Comment by Morgul** [comment]
Closing this, since the issue seems resolved.
