### ISSUE TITLE
Release new build with carousel-fix on NPMJS

### ISSUE THREAD

**Issue by wcoppens** [Morgul/ui-bootstrap4#5]
Now the carousel fixes are merged with the master it would be nice if this can be released on NPMJS.

**Comment by Morgul** [comment]
My plan is to tackle that today, if I have time.

**Comment by Morgul** [comment]
Just released `v3.0.0-beta.4`.

Man, the release system from `angular-ui/boostrap` is kinda awful... and my changes haven't made it any friendlier. ;)

**Comment by wcoppens** [comment]
Yeah i noticed the same...

**Comment by Morgul** [comment]
@wcoppens There was an issue with that release, and I did some more minor fixes.

`v3.0.0` has been released, now, and should be out on npm and working.
