### ISSUE TITLE
Plunker script source change

### ISSUE THREAD

**Issue by ElitenetDenmark** [Morgul/ui-bootstrap4#50]
All examples shown on website leads to a Plunker page.
The ui-bootstrap javascript code on those pages is 404. So they should be changed from:

From:
<script src="//angular-ui.github.io/bootstrap/ui-bootstrap-tpls-3.0.6.js"></script>

To:
<script src="https://morgul.github.io/ui-bootstrap4/ui-bootstrap-tpls-3.0.6.min.js"></script>

**Comment by ElitenetDenmark** [comment]
Ok fixed.


[plunker.zip](https://github.com/Morgul/ui-bootstrap4/files/3658515/plunker.zip)

**Comment by Morgul** [comment]
@ElitenetDenmark Could you please make a merge request?
