### ISSUE TITLE
Remove console.log in position.src

### ISSUE THREAD

**Issue by mysticfall** [Morgul/ui-bootstrap4#6]
Currently, `position.js` contains an unnecessary logging statement that spams the browser console:

https://github.com/Morgul/ui-bootstrap4/blob/e5946fdb6756190728e6aaa4d008e69f65b307b8/src/position/position.js#L629

It might be better if it could be removed or made configurable.

**Comment by Morgul** [comment]
Ah, that's definitely a mistake.

**Comment by Morgul** [comment]
`v3.0.0` has been released with this fix, and should be out on npm.
