### ISSUE TITLE
Requiring ui-bootstrap4 returns module name

### ISSUE THREAD

**Issue by septagram** [Morgul/ui-bootstrap4#60]
I have a quick question:
```
require ('ui-bootstrap4')
```
returns `'ui.bootstrap'` instead of the actual module. My experience with AngularJS is insufficient to speak with confidence, but isn't the convention to return a module instead, and allow accessing module name via `.name`?

I'm asking, because one of the possible conventions for module loading is:
```
angular.module ('app, [
    require ('angular-hotkeys').name, // most modules are cool with this
    ...
    require ('ui-bootstrap4').name, // oops! could not load module undefined
])
```
...and returning name breaks this convention. If the convention exists, this should be a quick fix, I think I should be able to make a PR.

**Comment by Morgul** [comment]
While I don't disagree with you, that decisions was made long before I took over maintenance of the project. As this is mainly intended as a stop-gap solution anyway, I have no intention of changing how this works; my chief audience is  people already using `ui.bootstrap` in legacy code, who need an upgrade path to bootstrap 4, while they port their legacy UI to something new. (This way the new and old UI code can share a CSS framework.)

I would **strongly** discourage development of new code using this library, or adding this library to legacy code, if you're not already using it.

**Comment by septagram** [comment]
Understood. Fair point, I agree with you; this change would actually break code that relies on returning a module name. And no, I'm of course not developing new code with **ui-bootstrap4** ))
