### ISSUE TITLE
Modal: Add support for .modal-dialog-scrollable

### ISSUE THREAD

**Issue by modmatrix** [Morgul/ui-bootstrap4#61]
It'd be nice (and pretty easy) to add support for the .modal-dialog-scrollable class:

https://getbootstrap.com/docs/4.4/components/modal/#scrolling-long-content

Right now, it isn't possible to use this feature without resorting to hacks.

(I might submit a pull request for this when I have time – this issue is just a reminder for myself, or someone else, to do that.)

**Comment by videk1** [comment]
Please add support for this. Much needed!

**Comment by Morgul** [comment]
I would be fine if someone wants to add that. I'll gladly review the code and merge it in. I, however, am doing active development on this project, so this will have to come from the community.

**Comment by doublesharp** [comment]
@Morgul - this tripped me up because in the 3.0.7 version the dist/ui-bootstrap.js version is still at 3.0.6. The 3.0.7 ones have the version in the filename, but it was unexpected for them to not match, so by including the file without the version in the name this functionality was missing.
