### ISSUE TITLE
missing template on version 3.0.1

### ISSUE THREAD

**Issue by vindemasi** [Morgul/ui-bootstrap4#9]
Hello,

first of all many thanks for your work. Then a few words to describe the issue.

### Bug description:
It seems the 'accordion-group.html' is missing from 'ui-bootstrap.tpls'. However the version '3.0.0' works like a charm.

### Steps to reproduce the issue:
The AngularJS app does not work at all, and throws error during start.

### Version of Angular, UIBS, and Bootstrap

Angular: 1.6.8

UIBS: 3.0.1

Bootstrap: 4.0.0

Have a nice day.

**Comment by Morgul** [comment]
Seems like there was a build issue. I'll try and look at it today.

**Comment by Morgul** [comment]
I just published v3.0.2, which should have everything included, now. Let me know if there's still an issue, and I'll reopen this.

**Comment by vindemasi** [comment]
Thank you very much @Morgul, it seems to be working again.
